#!/data/data/com.termux/files/usr/bin/bash
clear
echo -e "\e[34m=========================================\e[0m"
echo -e "\e[1;32m         TermuxPlus Command Menu         \e[0m"
echo -e "\e[34m=========================================\e[0m"
echo "Type any of these 16 commands to use them:"
echo ""
echo -e "\e[33m1. login\e[0m       - System time security access verification"
echo -e "\e[33m2. csds\e[0m        - Physical micro SD card storage diagnostics"
echo -e "\e[33m3. settings\e[0m    - Version update check and profile utility"
echo -e "\e[33m4. info\e[0m        - Displays device hardware and CPU data"
echo -e "\e[33m5. backup\e[0m      - Backs up home directory to storage"
echo -e "\e[33m6. clean\e[0m       - Wipes system cache to free up gigabytes"
echo -e "\e[33m7. network\e[0m     - Displays current ping and IP routing speed"
echo -e "\e[33m8. theme\e[0m       - Customizes background terminal colors"
echo -e "\e[33m9. weather\e[0m     - Pulls active local weather forecasts"
echo -e "\e[33m10. syslock\e[0m    - Locks terminal window with password protection"
echo -e "\e[33m11. sysstatus\e[0m  - Real-time tracking of RAM and active processes"
echo -e "\e[33m12. battery\e[0m    - Checks precise battery health and charging metrics"
echo -e "\e[33m13. filemanager\e[0m- Light command-line directory navigation tool"
echo -e "\e[33m14. uninstaller\e[0m- Clean removal suite for this entire environment"
echo -e "\e[33m15. webcheck\e[0m   - Verifies site status and network uptime loops"
echo -e "\e[33m16. helpme\e[0m     - Launches this interactive user command manual"
echo -e "\e[34m=========================================\e[0m"
