#!/data/data/com.termux/files/usr/bin/bash
clear
echo -e "\e[34m=========================================\e[0m"
echo -e "\e[1;35m 🚀 Termux+ 1.0.2: S6 Lite Power Suite \e[0m"
echo -e "\e[34m=========================================\e[0m"
echo "Available 9-Command Core Toolkit:"
echo ""
echo -e "\e[33m1. subfind\e[0m      - Lightning-fast subdomain discovery"
echo -e "\e[33m2. editf\e[0m        - Quick-launch terminal text editing"
echo -e "\e[33m3. lsa\e[0m          - Enhanced visibility for hidden & system files"
echo -e "\e[33m4. nload\e[0m        - Streamlined file saving and loading mechanics"
echo -e "\e[33m5. copkg\e[0m        - Smart package installer with size previews"
echo -e "\e[33m6. scan-storage\e[0m - Visualizes storage breakdown on your device"
echo -e "\e[33m7. search\e[0m       - Instant command history search locator"
echo -e "\e[33m8. plus-toggle\e[0m  - Turn Termux+ system features on or off"
echo -e "\e[33m9. tp-disable\e[0m   - The Danger Zone uninstaller with safety alerts"
echo ""
echo -e "\e[32mStandard Utilities:\e[0m login, csds, settings"
echo -e "\e[34m=========================================\e[0m"
